version: '3'

services:
  backend:
    build:
      context: ./server
    command: gunicorn auction.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./client
    command: npm start
    ports:
      - "3000:80"
    volumes:
      - react_build:/react/build
volumes:
  react_build: