# Generated by Django 4.1 on 2022-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_playerresponse_groupr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_rating',
            field=models.FloatField(default=0),
        ),
    ]
