# Generated by Django 4.1 on 2022-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_player_final_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='dr',
            field=models.FloatField(default=0),
        ),
    ]
