# Generated by Django 4.1 on 2022-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_player_dr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canAccessFinalRatings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='canSelectTeam',
            field=models.BooleanField(default=False),
        ),
    ]
