# Generated by Django 4.1 on 2022-08-17 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_player_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canRatePlayers',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
