# Generated by Django 4.1 on 2022-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_canrateplayers_alter_team_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(related_name='teamplayers', to='core.team'),
        ),
    ]
