# Generated by Django 4.1 on 2022-08-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_team_total_score_alter_player_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groupr2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grpusers', to='core.groupr2'),
        ),
    ]
