# Generated by Django 4.1 on 2022-08-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_player_groupr2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='groupr2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='players', to='core.groupr2'),
        ),
    ]
