# Generated by Django 4.1 on 2022-08-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
